// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/network/protocol/domain/player.proto

package domain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginResponse_Status int32

const (
	LoginResponse_OK     LoginResponse_Status = 0
	LoginResponse_DENIED LoginResponse_Status = 1
)

var LoginResponse_Status_name = map[int32]string{
	0: "OK",
	1: "DENIED",
}

var LoginResponse_Status_value = map[string]int32{
	"OK":     0,
	"DENIED": 1,
}

func (x LoginResponse_Status) String() string {
	return proto.EnumName(LoginResponse_Status_name, int32(x))
}

func (LoginResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61a5d89c1271c4b6, []int{1, 0}
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61a5d89c1271c4b6, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Status               LoginResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=domain.LoginResponse_Status" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id                   string               `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61a5d89c1271c4b6, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() LoginResponse_Status {
	if m != nil {
		return m.Status
	}
	return LoginResponse_OK
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MoveCommand struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MoveCommand) Reset()         { *m = MoveCommand{} }
func (m *MoveCommand) String() string { return proto.CompactTextString(m) }
func (*MoveCommand) ProtoMessage()    {}
func (*MoveCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_61a5d89c1271c4b6, []int{2}
}

func (m *MoveCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveCommand.Unmarshal(m, b)
}
func (m *MoveCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveCommand.Marshal(b, m, deterministic)
}
func (m *MoveCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveCommand.Merge(m, src)
}
func (m *MoveCommand) XXX_Size() int {
	return xxx_messageInfo_MoveCommand.Size(m)
}
func (m *MoveCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveCommand.DiscardUnknown(m)
}

var xxx_messageInfo_MoveCommand proto.InternalMessageInfo

func (m *MoveCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MoveCommand) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func init() {
	proto.RegisterEnum("domain.LoginResponse_Status", LoginResponse_Status_name, LoginResponse_Status_value)
	proto.RegisterType((*LoginRequest)(nil), "domain.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "domain.LoginResponse")
	proto.RegisterType((*MoveCommand)(nil), "domain.MoveCommand")
}

func init() {
	proto.RegisterFile("pkg/network/protocol/domain/player.proto", fileDescriptor_61a5d89c1271c4b6)
}

var fileDescriptor_61a5d89c1271c4b6 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcf, 0x4e, 0xf3, 0x30,
	0x10, 0xc4, 0xbf, 0xe4, 0x93, 0x42, 0xd9, 0x42, 0x55, 0xf9, 0x14, 0x55, 0x3d, 0xa0, 0x9c, 0x2a,
	0x84, 0x62, 0xa9, 0xf4, 0x09, 0xa0, 0x45, 0x42, 0xe5, 0x9f, 0xc2, 0x8d, 0x9b, 0x9b, 0x58, 0xc1,
	0x4a, 0xed, 0x35, 0xb6, 0xd3, 0xaa, 0x0f, 0xc1, 0x3b, 0x23, 0x1c, 0xa7, 0x82, 0x0b, 0xc7, 0x99,
	0x9d, 0xdf, 0xee, 0x6a, 0x60, 0xa6, 0x9b, 0x9a, 0x2a, 0xee, 0xf6, 0x68, 0x1a, 0xaa, 0x0d, 0x3a,
	0x2c, 0x71, 0x4b, 0x2b, 0x94, 0x4c, 0x28, 0xaa, 0xb7, 0xec, 0xc0, 0x4d, 0xee, 0x6d, 0x92, 0x74,
	0xe6, 0xe4, 0xf2, 0x4f, 0x02, 0xad, 0x70, 0x02, 0x55, 0xc7, 0x64, 0x77, 0x70, 0xf6, 0x80, 0xb5,
	0x50, 0x05, 0xff, 0x68, 0xb9, 0x75, 0x64, 0x02, 0x83, 0xd6, 0x72, 0xa3, 0x98, 0xe4, 0x69, 0x74,
	0x11, 0xcd, 0x4e, 0x8b, 0xa3, 0xfe, 0x9e, 0x69, 0x66, 0xed, 0x1e, 0x4d, 0x95, 0xc6, 0xdd, 0xac,
	0xd7, 0xd9, 0x67, 0x04, 0xe7, 0x61, 0x91, 0xd5, 0xa8, 0x2c, 0x27, 0x0b, 0x48, 0xac, 0x63, 0xae,
	0xb5, 0x7e, 0xcf, 0x68, 0x3e, 0xcd, 0xbb, 0x0f, 0xf2, 0x5f, 0xb1, 0xfc, 0xd5, 0x67, 0x8a, 0x90,
	0x25, 0x29, 0x9c, 0x48, 0x6e, 0x2d, 0xab, 0x79, 0x38, 0xd1, 0x4b, 0x32, 0x82, 0x58, 0x54, 0xe9,
	0x7f, 0x6f, 0xc6, 0xa2, 0xca, 0xa6, 0x90, 0x74, 0x2c, 0x49, 0x20, 0x7e, 0x5e, 0x8f, 0xff, 0x11,
	0x80, 0x64, 0xb9, 0x7a, 0xba, 0x5f, 0x2d, 0xc7, 0x51, 0xb6, 0x86, 0xe1, 0x23, 0xee, 0xf8, 0x2d,
	0x4a, 0xc9, 0x54, 0x15, 0xe0, 0xa8, 0x87, 0xc9, 0x15, 0x0c, 0xfa, 0x22, 0xfc, 0x9d, 0xe1, 0x7c,
	0xdc, 0xbf, 0xf7, 0x12, 0xfc, 0xe2, 0x98, 0xb8, 0x59, 0xbc, 0xcd, 0x6b, 0xe1, 0xde, 0xdb, 0x4d,
	0x5e, 0xa2, 0xa4, 0x4a, 0x94, 0xcd, 0xc6, 0x1c, 0x98, 0xa2, 0x35, 0xee, 0x90, 0xd3, 0x9f, 0x6d,
	0xd7, 0x46, 0x97, 0xa1, 0xe9, 0x4d, 0xe2, 0x1b, 0xbe, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x12,
	0xf4, 0x76, 0x43, 0xc1, 0x01, 0x00, 0x00,
}
