name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
          
      - name: Install dependencies
        run: sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
        shell: bash

      - name: Check out source
        uses: actions/checkout@v1

      - name: Test Packages
        run: go test -v ./pkg/...
